language: ruby
rvm:
- 2.2.3
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproof ./_site --disable-external
after_success:
- "chmod +x ./bin/automated && ./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: vimcat
  - EMAIL: veronica@vimcat.com
  - secure: g966nVC+KYY5H/wfK0qP2gZ1x3wIvJTAJwWeqZRIy8N15ZZzGocFk9DMOxcbTPDN14EYHLyjWFl2YVna3R9f3xtvEtvTGxh53reiDE0TlwV37W+wE19iG2wwA5H/0PiGzSxm61rAAG1xWLt3fY3/piYlEfVGGdtfN2mVZV7mbfY=
sudo: false
