assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-16803129-1

gems:
  - jekyll-assets
  - jekyll-sitemap

name: 'Vimcat: Veronica Canterbury'

permalink: pretty

url: www.vimcat.com

timezone: America/Los_Angeles
